"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import Brand from "@/components/Brand";
export default function SignupForm(){
 const[n,setN]=useState("");const[e,setE]=useState("");const[p,setP]=useState("");const[err,setErr]=useState("");const[done,setDone]=useState(false);
 async function go(x:React.FormEvent){x.preventDefault();setErr("");const{error}=await createClient().auth.signUp({email:e,password:p,options:{data:{full_name:n}}});if(error)setErr(error.message);else setDone(true)}
 if(done)return <main className="auth"><div className="auth-orbit orbit-one"/><section className="auth-card"><Brand href="/cadastro"/><div className="eyebrow">QUASE LÁ</div><h1 className="auth-title">Confirme seu e-mail.</h1><p className="auth-sub">Enviamos a confirmação para <b>{e}</b>. Depois, você já poderá entrar no seu workspace.</p><a className="btn primary auth-submit" href="/login">Ir para o login</a></section></main>;
 return <main className="auth"><div className="auth-orbit orbit-one"/><div className="auth-orbit orbit-two"/><section className="auth-card"><Brand href="/cadastro"/><div className="eyebrow">NOVO WORKSPACE</div><h1 className="auth-title">Comece com o Messagefy.</h1><p className="auth-sub">Crie seu workspace para organizar contatos, grupos e campanhas.</p><form className="form" onSubmit={go}>{err&&<div className="error">{err}</div>}<div className="field"><label>Nome</label><input className="input" required value={n} onChange={x=>setN(x.target.value)} placeholder="Seu nome"/></div><div className="field"><label>E-mail</label><input className="input" type="email" required value={e} onChange={x=>setE(x.target.value)} placeholder="voce@empresa.com"/></div><div className="field"><label>Senha</label><input className="input" type="password" minLength={6} required value={p} onChange={x=>setP(x.target.value)} placeholder="Mínimo de 6 caracteres"/></div><button className="btn primary auth-submit" type="submit">Criar workspace</button></form><p className="auth-foot">Já possui uma conta? <a className="link" href="/login">Entrar</a></p></section></main>
}
